-- CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE EMPLOYEE
(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT VARCHAR(20),
SALARY INT NOT NULL
);
SELECT * FROM EMPLOYEE;
INSERT INTO EMPLOYEE
VALUES(101,"AMIT","IT",60000),
(102,"NEHA","HR",50000),
(103,"RAVI","IT",80000),
(104,"PRIYA","SALES",55000),
(105,"KARAN","FINANCE",70000),
(106,"SARA","HR",45000);

SELECT * FROM EMPLOYEE
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEE WHERE DEPT ="HR");

SELECT DEPT ,AVG_SALARY
FROM(
SELECT DEPT , AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEE
GROUP BY DEPT

)AS DEPT_SUMMARY
WHERE AVG_SALARY >55000;
